### ISSUE TITLE
Obligatory "Typescript Definitions?"

### ISSUE THREAD

**Issue by yliaho** [Javin-Ambridge/reddit-wrapper#1]
Hey, I've been looking something like this! Thank you!

Are you willing to accept PRs? Fancy TypeScript or are you familiar with it? I'd love to whip up a quick .d.ts file for the API options and the exposed HTTP request methods. In fact, I've already started it.

Let me know what you think! 😄

**Comment by Javin-Ambridge** [comment]
Ofcourse I am willing to accept PR's! Merging your PR right now, looks good, I definitely also do have a soft spot for TypeScript :)

**Comment by Javin-Ambridge** [comment]
Merged
